# Numpy Splitting Arrays  
*Splitting is the reverse operation of joining.*  
*Joining merges multiple arrays into one and splitting breaks single array into multiple.*  
*We use array_split() to split arrays, we pass array that we need to split along with the number of splits we want*

In [26]:
import numpy as np

In [27]:
arr=np.array([1,2,3,4,5,6])
s_arr=np.array_split(arr,3)
print(s_arr) 
print(type(s_arr))# return value is a list containing three arrays

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>


In [28]:
s_arr=np.array_split(arr,4)
print(s_arr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [29]:
s_arr=np.array_split(arr,2)
print(s_arr)

[array([1, 2, 3]), array([4, 5, 6])]


In [30]:
s_arr=np.array_split(arr,22)
print(s_arr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32)]


**NOTE :** *We also have the method split() available but it will not adjust the elements are less in source array for splitting 6 elements cannot be splitted into 4 arrays, but array_split() method will adjust elements accordingly and work properly.*

In [31]:
s_arr=np.array_split(arr,3)
print(s_arr)
print(s_arr[0])
print(s_arr[1])
print(s_arr[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


**Splitting 2-d array**

In [32]:
matrix=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])

new=np.array_split(matrix,2)
print(new)

for i in range(len(new)):
    print(new[i]) 

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[ 7,  8],
       [ 9, 10],
       [11, 12]])]
[[1 2]
 [3 4]
 [5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [33]:
matrix=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])

new=np.array_split(matrix,4)
print(new)

for i in range(len(new)):
    print(new[i]) 

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]]), array([[11, 12]])]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]]
[[11 12]]


In [34]:
matrix=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])

new=np.array_split(matrix,6)
print(new)

for i in range(len(new)):
    print(new[i]) 

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]]), array([[11, 12]])]
[[1 2]]
[[3 4]]
[[5 6]]
[[7 8]]
[[ 9 10]]
[[11 12]]


**Splitting alongs rows (axis=1)**

In [38]:
matrix=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])

new=np.array_split(matrix,2,axis=1)
print(new)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])]


**hsplit(), dpslit() and vsplit()**

In [40]:
array=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])

newarr=np.hsplit(array,3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [41]:
newarray=np.vsplit(array,3)
print(newarray)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


**dsplit() works only on array of 3 or more dimensions.**