# SEARCHING ARRAYS  
*You can search an array for a certain value, and return the indexes that get a match.*  
*To search an array use where() method.*

In [1]:
import numpy as np

In [11]:
arr=np.array([1,2,3,4,5,8,8,8])

x=np.where(arr==4)
print(x) # x will be tuple which will store index(s) of key which is being searched
print("Index :",x[0][0])

(array([3], dtype=int64),)
Index : 3


In [14]:
x=np.where(arr==8)
print(x)
print("Index :",x[0])
# (5,6,7) are the indexes where 8 is present.

(array([5, 6, 7], dtype=int64),)
Index : [5 6 7]


**Find the indexes where values are even**

In [15]:
array=np.array([1,2,3,4,5,6,7,8])

even=np.where(array%2==0)
print(even)

(array([1, 3, 5, 7], dtype=int64),)


**Find the indexes where values are odd**

In [16]:
odd=np.where(array%2==1)
print(odd)

(array([0, 2, 4, 6], dtype=int64),)


**We can perform element wise Logical AND (&) operation**

In [20]:
divisible=np.where((array%2==0) & (array%4==0))
print(divisible)

(array([3, 7], dtype=int64),)


**Logical OR (|) operation**

In [21]:
divisible1=np.where((array%2==0)|(array%4==0))
print(divisible1)

(array([1, 3, 5, 7], dtype=int64),)


**Search Sorted**  
*There is a method called searchsorted() which performs Binary Search in the array, and returns the index where specified value would be inserted to maintain search order.*  
*The searchsorted() is assumed to be working on sorted arrays.*

In [23]:
arr=np.array([1,2,3,4,7])
x=np.searchsorted(arr,5)
print(x) # At index x=4 we need to insert 5 so that array remains in sorted order

4


In [24]:
x=np.searchsorted(arr,[5,6])
print(x)

[4 4]


*Using side='right', we can get index from rightside*

In [28]:
x=np.searchsorted(arr,9,side='right')
print(x)

5
