# SLICING  
*Slicing in python means taking elements from one given index to another given index.*  
*arr[start : end : step]*

In [1]:
import numpy as np

**Slicing 1-d array**

In [2]:
array=np.array([1,2,3,4,5])
print(array)
print(type(array))
print(array.ndim)
print(array.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)


In [12]:
print(array[:])
print(array[:3])
print(array[2:])
print(array[2:4])
print(array[1:4:2])
print(array[::3])
print(array[::2])
print(array[-5:-1])
print(array[-5:0])
print(array[-3:-1])

[1 2 3 4 5]
[1 2 3]
[3 4 5]
[3 4]
[2 4]
[1 4]
[1 3 5]
[1 2 3 4]
[]
[3 4]


**Slicing 2-d array**  
*An array that has 1-d array as its elements is called 2-d array or matrix*

In [13]:
matrix=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(matrix)
print(type(matrix))
print(matrix.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
2


In [24]:
print(matrix[0,:])
print(matrix[0:2,:2])
print(matrix[0,:1])

[1 2 3]
[[1 2]
 [4 5]]
[1]


In [25]:
print(matrix[1,:])
print(matrix[1,1:3])
print(matrix[1:,:1])

[4 5 6]
[5 6]
[[4]
 [7]]


In [27]:
print(matrix[:,:])
print(matrix[:2,1:3])
print(matrix[2,:1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[7]
