# Array Indexing


*Array indexing is same as accessing an array element.*  
*You can access an array element by referring to its index numbers.*  
*Numpy array supports both 0-based as well as negative indexing.*

**Access 1-d array**

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,'a'])
print(arr)
print(type(arr))

# Upcasting is explained here
# Note: In Numpy, each array should have ideally the same data type for each element.
# But if array have different type of element then numpy will automatically promote the datatype of  array element to ensure consistency, this is 
# This is done in order to efficiently allocate memory and perform operations on the array. 
# example: int + float , every element will be promoted to float data type [1,2,3,4.3,4.8] = [1.0,2.0,3.0,4.3,3.8]
# example: int + str , every element will be promoted to string data type [1,2,3,4,'a'] = ['1','2','3','4','a']

['1' '2' '3' '4' 'a']
<class 'numpy.ndarray'>


In [4]:
print(arr[0])
print(type(arr[0]))

print(arr[-2])
print(type(arr[-2]))

print(arr[0]+arr[-2])
print(arr[0]+arr[-1])

1
<class 'numpy.str_'>
4
<class 'numpy.str_'>
14
1a


**Accessing 2-d array (matrix)**

In [5]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print(type(matrix))
print(matrix.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
2


In [10]:
print(matrix[0,1]) #[row,column] == [dimensions,index]
print(matrix[1,2])
print(matrix[2,0])

matrix[2,2]=matrix[0,1]+matrix[1,2]+matrix[2,0]
print(matrix)

2
6
7
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 15]]


**Accessing 3-d array**  
*An array that has 2d array as its element is called 3d array*

In [25]:
cube=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print(cube.ndim)
print(type(cube))

print(cube[0,0,2])
print(cube[1,1,0])
print(cube[2,1,2])

cube[2,1,1]=cube[0,0,2]+cube[1,1,0]+cube[2,1,2]
print(cube[-1,-1,-2])
print(cube[-2,-2,-1])
print(cube[-3,-1,-3])

3
<class 'numpy.ndarray'>
3
10
18
31
9
4
