# Shape of an Array  
*The shape of an array is the number of elements in each dimensions.*

In [1]:
import numpy as np

In [3]:
matrix=np.array([
    [1,2,3,4],
    [5,6,7,8]
])

print(matrix)
print(matrix.shape) # (2,4) first dimension has 2 elements and second dimension has 4 elements

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [6]:
cube=np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]]])

print(cube)
print(cube.shape) # (2,2,3) # first dimesnion has 2 elements, second dimesnion has 2 elements, and third dimension has 3 elements

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [9]:
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print(arr.shape) # (1,1,1,1,5)
# first dimenson has 1 element, second dimension has 1 elements, third dimension has 1 elements, fourth dimension has 1 element and fifth dimension has 5 elements

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


**What does Tuple reprsents ?**  
*Integers at every index tells about the number of elements corresponding dimensions have.*  
*Ex: value at index 4 is 5 which means fifth dimension has 5 elements*