# Sorting arrays  
*Sorting means putting elements in an ordered sequence.*  
*Ordered Sequence is any sequence that has an order corresponding to elements, like numeric or alphabet or ascending or descending.*  
*Sorting can be done using sort()*  

In [10]:
import numpy as np

**Note :** *sort() returns None , it means sort() gives copy of original arr, leaving original array unaffected by any changes*

In [11]:
arr=np.array([18,2,-3,40,5])
sortedarr=np.sort(arr)
print(sortedarr)
print(sortedarr.base) 

[-3  2  5 18 40]
None


**String array**

In [12]:
fruits=np.array(['guava','kiwi','oranges','apples'])
sortedfruits=np.sort(fruits)
print(sortedfruits)

['apples' 'guava' 'kiwi' 'oranges']


**Boolean array**

In [13]:
boolean=np.array([True,False,False,True,False])
print(np.sort(boolean))

[False False False  True  True]


**2-d array**

In [14]:
matrix=np.array([[-1,20,3],[40,-5,16]])
print(np.sort(matrix))

[[-1  3 20]
 [-5 16 40]]
