# Joining Numpy arrays  
*Joining means putting contents of two or more arrays in single array*  
*We pass sequence of arrays that we want to join to the concatenate() function, along with the aixs, if aixs is not explicitly passed, it is taken as 0.*

In [16]:
import numpy as np

In [17]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7])

# By default axis=0
arr=np.concatenate((arr1,arr2))
print(arr)

# Passing axis=1 (along rows)
'''For 1-d array axis=1 is out of bounds'''
# array=np.concatenate((arr1,arr2),axis=1) 
# print(array)



[1 2 3 4 5 6 7]


'For 1-d array axis=1 is out of bounds'

In [18]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

arr=np.concatenate((arr1,arr2))
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


**Joining Arrays using Stack Functions**  
*Stacking is same as concatenation, the only difference is that stacking is done along new axis.*  
*We can concatenate 2 1-d array along second aixs which would result them putting one over other ie stacking.*  
*Using stack() functions.*

In [20]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

# stacking along columns

arr=np.stack((arr1,arr2))
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [21]:
# stacking along depth
arr=np.stack((arr1,arr2),axis=1)
print(arr)
print(arr.ndim)

[[1 4]
 [2 5]
 [3 6]]
2


**Stacking along rows**

In [22]:
arr=np.hstack((arr1,arr2))
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


**Stacking along columns**

In [23]:
arr=np.vstack((arr1,arr2))
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


**Stacking along Depth**

In [24]:
arr=np.dstack((arr1,arr2))
print(arr)
print(arr.ndim)

[[[1 4]
  [2 5]
  [3 6]]]
3
