# Numpy Filter Array  
*Filtering is the process of getting some elements out of an existing array and make a new array out of them.*  
*In numpy you can filter the array using boolean Indexing list.*

*A boolean indexing list is a list of booleans corresponding to particular index.*  
*If value at that index is True, then that elements is contained in the filter array and if value at that index is False, then that element is not contained in the filter array.*

**Hard coded Filter array**

In [9]:
import numpy as np

In [10]:
arr=np.array([1,2,3,4,5,6])
filter_arr=[True,False,False,True,False,True]

newarr=arr[filter_arr]
print(newarr)

[1 4 6]


**Creating the filter array**

In [11]:
age=np.array([21,24,35,27,26])

filter_arr=[]

for val in np.nditer(age):
    if val>25:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

print(filter_arr)

newarr=age[filter_arr]
print(newarr)

[False, False, True, True, True]
[35 27 26]


**Create a filter array that will only return even numbers**

In [12]:
number=np.array([12,17,2,9,66,46,9])

even=[]
for val in np.nditer(number):
    if val%2==0:
        even.append(True)
    else:
        even.append(False)

print(even)

evenarr=number[even]
print(evenarr)

[True, False, True, False, True, True, False]
[12  2 66 46]


**Creating filter directly from array**

In [13]:
number1=np.array([29,14,7,18,8,9])

filter_arr1=number1%2==1
print(filter_arr1)

newarr=number1[filter_arr1]
print(newarr)

[ True False  True False False  True]
[29  7  9]


In [14]:
height=np.array([150,167,178,181,166,158])

filter=height>160
print(filter)

newarr=height[filter]
print(newarr)

[False  True  True  True  True False]
[167 178 181 166]
