**Tensor**  
*It is a fundamental concept in Linear Algebra for any kind of ML algorithms.*  
*In maths, a Tensor is an algebraic object that describes a mutli-linear relation between sets of algebraic object related to vector space.*  
*Scalar - 0-d Tensor - value*  
*Vector - 1-d Tensor - array*  
*Matrix - 2-d Tensor - matrix*  
*Cube - 3-d Tensor - cube*  

# Arrays

*Numpy is used to work with arrays. The array object in Numpy is called  ndarray.*  
*We can create ndarray using array() function*

In [1]:
import numpy as np 

In [3]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# We can also pass Tuple in array()
array=np.array((1,2,3,4,))
print(array)
print(type(array))

[1 2 3 4]
<class 'numpy.ndarray'>


**Dimension - A dimension in arrays is one level of array depth (nested arrays).**

**0-d arrays - SCALARS**

In [6]:
scalar=np.array(27)
print(scalar)
print(type(scalar))
print(scalar.shape)

27
<class 'numpy.ndarray'>
()


**1-d arrays - Arrays**  
*An array that has 0-d array as its elements is called 1-d arrays*

In [7]:
arr1=np.array([10,20,30,40,50])
print(arr1)
print(type(arr1))
print(arr1.shape)

[10 20 30 40 50]
<class 'numpy.ndarray'>
(5,)


**2-d arrays - Matrix**  
*An array that has 1-d array as its element is called is called 2-d arrays.*

In [8]:
matrix=np.array([[1,2,3],[4,5,6]])
print(matrix)
print(type(matrix))
print(matrix.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


**3-d arrays - Cube**  
*An array that has 2-d array as its element is called is called 3-d array.*

In [10]:
cube=np.array([[[1,2,3],[4,5,6]],[['a','b','c'],['c','d','e']]])
print(cube)
print(type(cube))
print(cube.shape) # (2,2,3) it means there are 2 tables(2-d array/matrix) each with 2 rows and 3 columns

[[['1' '2' '3']
  ['4' '5' '6']]

 [['a' 'b' 'c']
  ['c' 'd' 'e']]]
<class 'numpy.ndarray'>
(2, 2, 3)


**Check number of dimensions**

In [11]:
print(arr.ndim)
print(arr1.ndim)
print(array.ndim)
print(scalar.ndim)
print(matrix.ndim)
print(cube.ndim)

1
1
1
0
2
3


**Higher Dimensional Arrays**  
*An array can have any number of dimensions.*
*When an array is created you can define the number of dimensions using ndmin() argument.*

In [14]:
ndim_array=np.array([1,2,3,4,5],ndmin=5)
print(ndim_array)
print(type(ndim_array))
print(ndim_array.shape) # (1,1,1,1,5) first d has 1 element 2nd d has 1 element....last d has 5 elements

[[[[[1 2 3 4 5]]]]]
<class 'numpy.ndarray'>
(1, 1, 1, 1, 5)
