# ARRAY RESHAPE  
*Reshaping means changing the shape of array.*  
*The shape of an array is the number of elements in each dimensions.*  
*By reshaping, we can add or remove the dimension or change number of elements in each dimensions.*

**Reshaping 1-d array to 2-d array**

In [21]:
import numpy as np

In [22]:
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(3,2)
# newarr=arr.reshape(2,2) # ValueError: cannot reshape array of size 6 into shape (2,2)

print(arr.ndim)
print(newarr.ndim)

print(arr)
print(newarr)

print(arr.base)
print(newarr.base) # it means reshape gives view of original array, hence any changes in view will also be reflected in original array and vice-versa.

newarr[2][0]=189
print(newarr)
print(arr)

1
2
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
None
[1 2 3 4 5 6]
[[  1   2]
 [  3   4]
 [189   6]]
[  1   2   3   4 189   6]


**Unknow dimension**  
*We are allowed to have one 'unknown' dimension.*  
*Meaning that you don't have to specify an exact number for one of the dimensions in the reshape method.*  
*Pass -1 , and numpy will calculate unknown dimension for you.*  
*We cannot pass -1 to more than one dimensions.*

**Reshape 1-d array to 3-d array**

In [26]:
array=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
cube=array.reshape(3,2,2)

print(array)
print(cube)

print(array.ndim)
print(cube.ndim)

print(array.base)
print(cube.base) # it is a view of original array

cubic=array.reshape(-1,2,3) # -1 is unknown dimension , so numpy will caluclate it for me.
print(cubic)

# Flattening a 1-d array

arr1=cubic.flatten()
print(arr1)

arr1=cube.reshape(-1)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
1
3
None
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
