# The difference between copy and view  
*The main difference b/w copy and view of an array is that copy is a new array and view is just the view of original array.*  
*The copy owns the data and any changes made to copy will not affect original array and any changes made to original array will not affect copy.*  
*The view does not owns the data and any changes made to view will affect original array and any changes made to original array will affect view.*

**COPY**

In [14]:
import numpy as np

In [15]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
print(arr)
print(x)

[1 2 3 4 5]
[1 2 3 4 5]


In [16]:
x[0]=10
print(x)
print(arr)

[10  2  3  4  5]
[1 2 3 4 5]


In [17]:
arr[0]=89
print(arr)
print(x)

[89  2  3  4  5]
[10  2  3  4  5]


In [18]:
# base is an attribute of Numpy array that returns None if arrays owns data otherwise refers to original object.
print(arr.base)
print(x.base) # since x is a copy, so it returns None 

None
None


**VIEW**

In [19]:
array=np.array([1,2,3,4,5])
x=array.view()
print(array)
print(x)

[1 2 3 4 5]
[1 2 3 4 5]


In [20]:
array[0]=10
print(array)
print(x)

[10  2  3  4  5]
[10  2  3  4  5]


In [21]:
x[0]=29
print(x)
print(array)

[29  2  3  4  5]
[29  2  3  4  5]


In [22]:
# base is an attribute of Numpy array that returns None if array owns the data, otherwise returns the object that owns the data or original object.
print(array.base)
print(x.base) # since x is a view it returns original object

None
[29  2  3  4  5]
